name: Android CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build App with Gradle
      run: ./gradlew assembleDebug
    - name: Testing fudi-store
      run: ./gradlew assembleDebug lint testDebugUnitTest -p fudi-permission
    - name: Upload Testing fudi-permission
      uses: actions/upload-artifact@v1
      with:
        name: fudi-permission-test
        path: fudi-permission/build/reports/tests/testDebugUnitTest
    - name: Upload fudi-store artifact
      uses: actions/upload-artifact@v1
      with:
        name: fudi-permission-aar
        path: fudi-permission/build/outputs/aar/fudi-permission-debug.aar
    - name: Rename aar kotlin
      run: mv fudi-permission/build/outputs/aar/fudi-permission-debug.aar fudi-permission.aar
    - name: Upload Assets
      uses: meeDamian/github-release@2.0
      with:
        allow_override: true
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        name: Latest Relese
        body: >
          This release actually.  
        files: >
          fudi-store.aar
